### ISSUE TITLE
Linux (Steam) Support missing

### ISSUE THREAD

**Issue by sehraf** [mircearoata/SatisfactoryModLauncherAPI#5]
As discussed here https://github.com/satisfactorymodding/SatisfactoryModManager/issues/47 moddings Satisfactory on Linux (with the Steam version) works fine out-of-the box but needs to be done by hand.

**Comment by mircearoata** [comment]
As an update on this, I looked a bit into it a couple of days ago, and it looks both easier and more difficult that I expected.

Easier because it looks like winegcc solves the problem of using Windows.h to read symbols from the dll.

And more difficult because there are multiple ways of installing Steam on linux and while the simple way (apt-get or snap) installs where the other person said, I had to install it via flatpak because of the CUDA issue, which turns out installs it somewhere else, so SMM needs to find that somewhere else. It might be as easy as `flatpak ls` or something, but I didn't have time to check

**Comment by folknor** [comment]
Please mircearoata, like I said in the other issue ticket, just check the default install folder (/home/userid/.steam), and if not found there just tell the user to select the folder themselves. And allow users to select/change the folder even if you find Steam there. As Linux users, we might have several Steam installs on our system.

That is the best option for users, the easiest option for users, and the easiest option for you.

You might think I am wrong about this, but then make a poll and give it only to Linux users. I can assure you we would _prefer_ to select the install folder versus automagic that works even 95% of the time. And the best you'd do is probably something that works 80% of the time.

I've been a core systems developer and Linux user for over 20 years, and a wine user for 18 years. My opinion is probably not entirely nonsense.

**Comment by sehraf** [comment]
Must agree with @folknor. `/home/user/.steam` will work fine on my system and yeah, there might be people out there who have multiple installations.

**Comment by x10an14** [comment]
I'd also like to throw my support in with @folknor's comment/feedback.

**Comment by ZengineerIO** [comment]
I'd love to see proton support aswell. 

Regarding the steam directories and possible flatpak installations, [here](https://github.com/patrickm32/proton-ge-custom-updater/blob/master/proton-ge-custom-updater) is how a custom proton update script looks for steam installations on linux.

`$HOME/.steam` is just a symlink to `$HOME/.local/share/Steam` for example. I hope this helps you.

Best regards

**Comment by TraceyC77** [comment]
Echoing my support for this request and say that I'm willing to help test on Ubuntu.

**Comment by mircearoata** [comment]
With the release of SMM API 2.1.0 and now the actual SMM (v2.2.0), Linux is natively supported, for both Epic and Steam
